### ISSUE TITLE
[Input] suffixText & prefixText style issues when set via property

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#10959]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Actual Behavior

The input styles rely on the `suffix-text` attribute, however the property isn't reflected so the attribute will not be there if the property is used.

### Expected Behavior

The styles work for both attributes and properties of suffixText, prefixText

### Reproduction Sample

https://codepen.io/driskull/pen/YPKyrJL?editors=1010

### Reproduction Steps

1. open codepen
2. notice the input set via property looks different than the one set via attributes

### Reproduction Version

3.0.0-next.44

### Relevant Info

The following style selector also looks to be incorrect:

```scss
:host([suffix-text]) input,
.element-wrapper:has(.clear-button) input,
:host([number-button-type="vertical"][type="number"]) input,
:host([suffix-text][number-button-type="horizontal"]) .suffix,
:host([suffix-text][number-button-type="vertical"][type="number"]) .suffix,
:host([number-button-type="vertical"][type="number"])
  .clear-button
  :host([number-button-type="horizontal"][type="number"])
  .clear-button {
  border-start-end-radius: 0;
  border-end-end-radius: 0;
}
```

### Priority impact

impact - p1 - need for current milestone

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A
