### ISSUE TITLE
[combobox, combobox-item] Add `--calcite-combobox-divider-color` and deprecate `--calcite-combobox-item-border-color`

### ISSUE THREAD

**Issue by Elijbet** [Esri/calcite-design-system#12226]
### Check existing issues

- [x] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Add `--calcite-combobox-divider-color` and deprecate `--calcite-combobox-item-border-color`.

### Acceptance Criteria

- new `--calcite-combobox-divider-color` added
- `--calcite-combobox-item-border-color` deprecated

### Relevant Info

Issue prompted by this [comment](https://github.com/Esri/calcite-design-system/pull/12150#pullrequestreview-2862829638). 

`--calcite-combobox-divider-color` makes the most sense since it is at the `combobox` level and not a border around the `combobox` or `combobox-item` (implemented internally)

### Which Component

combobox
combobox-item

### Priority impact

impact - p3 - not time sensitive

### Calcite package

- [x] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/calcite-ui-icons
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by geospatialem** [comment]
Verified the `--calcite-combobox-divider-color` css var, and deprecated `--calcite-combobox-item-border-color` on the `dev` branch and usage on `3.3.0-next.19`:

```css
/* New */
calcite-combobox {
  --calcite-combobox-divider-color: red;
}

/* Deprecated */
calcite-combobox {
  --calcite-combobox-item-border-color: red;
}
```
