### ISSUE TITLE
Global CSS file has grown 5000 lines.

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-design-system#7325]
### Description

1. Can we reduce the file size of the calcite.css style sheet? The CSS file grew from ~300 lines to ~5300 lines. So basically 5000 new lines. 
    
    1.3.0: https://cdn.jsdelivr.net/npm/@esri/calcite-components@1.3.0/dist/calcite/calcite.css
    1.4.0: https://cdn.jsdelivr.net/npm/@esri/calcite-components@1.4.0/dist/calcite/calcite.css

2. Can we move the animation classes into a new file for utility classes that can be used by teams if necessary. We can document this new file and its utility classes. The animation keyframes should also be renamed to be BEM so that they do not have any conflicts.

```css
@keyframes in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
```

3. Remove the `overflow-hidden` class only being used by modal. This could change to an inline style where Modal can just set the overflow to hidden on the document instead of using a class.

```css
.overflow-hidden {
  overflow: hidden;
}
```

4. Remove the following, it should be done in a components CSS not in the global CSS. 
```css
host([hidden]) {
  display: none;
}
```

### Proposed Advantages

Reduced file size, no conflicting code, utility classes are separated and documented properly.

### Which Component

All

- [x] Refactor utility classes (Matt, Adam)
- [ ] Refactor tokens (Ali, Franco)

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
