### ISSUE TITLE
Separate background color variables for the calcite-dialog would be very helpful

### ISSUE THREAD

**Issue by jesseadamsnpgs** [Esri/calcite-design-system#8614]
### Check existing issues

- [X] I have [checked for existing issues](https://github.com/Esri/calcite-design-system/issues) to avoid duplicates

### Description

Currently the --calcite-modal-content-background variable works well for customizing the background color of the modal content, however, there isn't a clear way to customize only the modal header or footer background colors. The --calcite-ui-foreground-1 variable is used as the header background color, however, changing that variable results in also changing the header and footer background colors. It would be great if the header, content, and footer had separate CSS variables for more flexible targeted styling.

### Acceptance Criteria

Separate background color override selectors, ie:

--calcite-modal-header-background
--calcite-modal-footer-background

### Which Component

calcite-modal

### Priority impact

p4 - not time sensitive

### Calcite package

- [X] @esri/calcite-components
- [ ] @esri/calcite-components-react
- [ ] @esri/calcite-design-tokens
- [ ] @esri/eslint-plugin-calcite-components

### Esri team

N/A

**Comment by ellenupp** [comment]
Dashboards team is also interested in this. 

We'll be introducing user-configurable "information windows" and would like more flexible styling options, specifically being able to target only the header background:

![image](https://github.com/Esri/calcite-design-system/assets/14304581/ed5feedc-a51c-4bea-9d0e-de6496c69b49)

A separate CSS variable for the header would be great.

**Comment by geospatialem** [comment]
With the deprecation of the `modal` component, in favor of `dialog` - re-scoping the title of the request to `dialog`. Implementation timeline TBD after the initial token effort makes headway in #7180 ✨

**Comment by macandcheese** [comment]
This can leverage the tokens introduced here in Panel https://github.com/Esri/calcite-design-system/pull/10822

**Comment by geospatialem** [comment]
Verified in `3.0.0-next.68` with the following tokens:
- `--calcite-dialog-background-color`
- `--calcite-panel-header-background-color`
- `--calcite-panel-footer-background-color`

```css
#my-custom-dialog {
  --calcite-dialog-background-color: var(--calcite-color-background);
  --calcite-action-background-color: var(--calcite-color-brand);
  --calcite-action-background-color-hover: var(--calcite-color-brand-hover);
  --calcite-action-background-color-pressed: var(--calcite-color-brand-pressed);
  --calcite-action-text-color: #000;
  --calcite-action-text-color-pressed: #000;
  --calcite-action-text-color-hover: #000;
  --calcite-panel-header-background-color: var(--calcite-color-brand);
  --calcite-panel-footer-background-color: var(--calcite-color-border-3);
}
```

![image](https://github.com/user-attachments/assets/6b5fe0a0-b1e8-415a-8de2-00e2ef81aa64)
